# Get editor completions based on the config schema
"$schema" = 'https://starship.rs/config-schema.json'

# Inserts a blank line between shell prompts
add_newline = true

# Replace the '❯' symbol in the prompt with '➜'
[character] # The name of the module we are configuring is 'character'
success_symbol = '[➜](bold green)' # The 'success_symbol' segment is being set to '➜' with the color 'bold green'

# Disable the package module, hiding it from the prompt completely
[package]
disabled = true

# Configure the directory module
[directory]
# The maximum number of directories to show in a path, 3 will show 3 directories, or fewer if there aren't so many
truncation_length = 3
# Use fish shell style path contraction, will show "~/a/b/c" as "~/a/…/c"
fish_style_pwd_dir_length = 4
