
#
# NAME
#   br - Broot file manager with shell command execution
#
# SYNOPSIS
#   br [OPTIONS] [PATH]
#
# DESCRIPTION
#   Broot is a terminal file manager and tree explorer. This Fish function wrapper
#   enables broot to execute shell commands (like cd) that affect the current
#   shell session, which normally wouldn't work from a subshell.
#
#   When you use broot's :cd command or other shell-affecting operations, broot
#   writes the command to a temporary file, which this function then executes in
#   the current shell.
#
# OPTIONS
#   All options are passed through to the broot command.
#
# ARGUMENTS
#   PATH
#       Starting directory for broot (defaults to current directory)
#
# FEATURES
#   - File tree visualization and navigation
#   - Interactive filtering and search
#   - Shell command execution (:cd, :rm, etc.)
#   - File operations (move, copy, delete)
#   - Preview panel for file contents
#
# DEPENDENCIES
#   broot (file manager)
#
# EXAMPLES
#   br                       # Launch broot in current directory
#   br ~/.config             # Launch broot in config directory
#   br --hidden              # Show hidden files
#
# BRROOT COMMANDS
#   In broot interface:
#   - :cd <path>             # Change directory (works via this wrapper)
#   - :rm <file>             # Remove file
#   - :trash <file>          # Move to trash
#   - :cp <src> <dst>        # Copy file
#   - :mv <src> <dst>        # Move file
#   - :mkdir <dir>           # Create directory
#   - ?                      # Show help
#
# NOTES
#   This wrapper is essential for broot commands that affect the shell state.
#   Without it, commands like :cd would only affect a subshell.
#
# SEE ALSO
#   broot(1) tree(1) ranger(1)
#
# This script was automatically generated by the broot program
# More information can be found in https://github.com/Canop/broot
# This function starts broot and executes the command it produces, if any.
# It's needed because some shell commands, like `cd`, have no useful effect if executed in a subshell.
#
function br --wraps=broot --description "Broot file manager with shell command execution"
    set -l cmd_file (mktemp)
    if broot --outcmd $cmd_file $argv
        read --local --null cmd < $cmd_file
        rm -f $cmd_file
        eval $cmd
    else
        set -l code $status
        rm -f $cmd_file
        return $code
    end
end
