wtf:
  colors:
    border:
      focusable: darkslateblue
      focused: orange
      normal: gray
  grid:
    columns: [32, 52, 32, 32, 90]
    rows: [5, 11, 11, 4, 4, 90]
  refreshInterval: 1
  mods:
    clocks_a:
      colors:
        rows:
          even: "lightblue"
          odd: "white"
      enabled: true
      locations:
        Vancouver: "America/Vancouver"
        Toronto: "America/Toronto"
        Paris: "Europe/Paris"
      position:
        top: 0
        left: 1
        height: 1
        width: 1
      refreshInterval: 15
      sort: "alphabetical"
      title: "Clocks A"
      type: "clocks"

    logger:
      enabled: true
      colors:
        label: "green"
        text: "white"
      position:
        top: 0
        left: 0
        height: 4
        width: 1
      refreshInterval: 15

    hackernews:
      enabled: true
      feeds:
        - https://news.ycombinator.com/rss
      feedLimit: 10
      position:
        top: 1
        left: 1
        height: 1
        width: 2
      type: feedreader

    uptime:
      args: [""]
      cmd: "uptime"
      enabled: true
      position:
        top: 4
        left: 1
        height: 1
        width: 2
      refreshInterval: 30
      type: cmdrunner

    info:
      enabled: true
      feeds:
        - http://feeds.bbci.co.uk/news/rss.xml
        - https://www.lemonde.fr/rss/en_continu.xml
        - https://www.theatlantic.com/feed/all/
      feedLimit: 10
      position:
        top: 2
        left: 1
        width: 2
        height: 2
      refreshInterval: 14400
      type: feedreader

    cryptolive:
      enabled: true
      position:
        top: 5
        left: 0
        height: 1
        width: 1
      updateInterval: 15
      currencies:
        BTC:
          displayName: Bitcoin
          to:
            - USD
            - EUR
            - ETH
        ETH:
          displayName: Ethereum
          to:
            - USD
            - EUR
            - BTC
      top:
        BTC:
          displayName: Bitcoin
          limit: 5
          to:
            - USD
      colors:
        from:
          name: coral
          displayName: grey
        to:
          name: white
          price: green
        top:
          from:
            name: grey
            displayName: coral
          to:
            name: red
            field: white
            value: green
